data:
  trump_path: 'data/raw/hashtag_donaldtrump.csv'
  biden_path: 'data/raw/hashtag_joebiden.csv'
  output_path: 'data/cleaned/english_tweets.csv'
  results_path: 'data/results/'

filter:
  country: 
    - 'United States'
    - 'United States of America'
  state_names:
    - 'Alabama'
    - 'Alaska'
    - 'Arizona'
    - 'Arkansas'
    - 'California'
    - 'Colorado'
    - 'Connecticut'
    - 'Delaware'
    - 'Florida'
    - 'Georgia'
    - 'Hawaii'
    - 'Idaho'
    - 'Illinois'
    - 'Indiana'
    - 'Iowa'
    - 'Kansas'
    - 'Kentucky'
    - 'Louisiana'
    - 'Maine'
    - 'Maryland'
    - 'Massachusetts'
    - 'Michigan'
    - 'Minnesota'
    - 'Mississippi'
    - 'Missouri'
    - 'Montana'
    - 'Nebraska'
    - 'Nevada'
    - 'New Hampshire'
    - 'New Jersey'
    - 'New Mexico'
    - 'New York'
    - 'North Carolina'
    - 'North Dakota'
    - 'Ohio'
    - 'Oklahoma'
    - 'Oregon'
    - 'Pennsylvania'
    - 'Rhode Island'
    - 'South Carolina'
    - 'South Dakota'
    - 'Tennessee'
    - 'Texas'
    - 'Utah'
    - 'Vermont'
    - 'Virginia'
    - 'Washington'
    - 'West Virginia'
    - 'Wisconsin'
    - 'Wyoming'
    - 'District of Columbia'

vectorizer:
  count:
    type: "count"
    max_features: 1000 #Maxmimum features
    max_df: 0.5 
  tfidf:
    type: "tfidf" 
    max_features: 1000 #Maximum features
    max_df: 0.5

streamlit:
  port: 8501
  data: 'data/results/sample_data.csv'
  geojson_url: 'https://raw.githubusercontent.com/PublicaMundi/MappingAPI/master/data/geojson/us-states.json'
  
